// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProfile(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddProfile'](arg1, arg2, arg3);
}

export function ClearHostsEntries(arg1) {
  return window['go']['main']['App']['ClearHostsEntries'](arg1);
}

export function CreateHostsBackup(arg1) {
  return window['go']['main']['App']['CreateHostsBackup'](arg1);
}

export function DedupHosts(arg1) {
  return window['go']['main']['App']['DedupHosts'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function ExportHostsToDialog(arg1) {
  return window['go']['main']['App']['ExportHostsToDialog'](arg1);
}

export function GetHostsText(arg1) {
  return window['go']['main']['App']['GetHostsText'](arg1);
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function GetProxyAddress(arg1) {
  return window['go']['main']['App']['GetProxyAddress'](arg1);
}

export function GetProxyLogs(arg1, arg2) {
  return window['go']['main']['App']['GetProxyLogs'](arg1, arg2);
}

export function ImportHostsFromDialog(arg1) {
  return window['go']['main']['App']['ImportHostsFromDialog'](arg1);
}

export function IsAdmin() {
  return window['go']['main']['App']['IsAdmin']();
}

export function ListHostsBackups(arg1) {
  return window['go']['main']['App']['ListHostsBackups'](arg1);
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function RenameProfile(arg1, arg2) {
  return window['go']['main']['App']['RenameProfile'](arg1, arg2);
}

export function ResetHostsTemplate(arg1) {
  return window['go']['main']['App']['ResetHostsTemplate'](arg1);
}

export function RestoreHostsBackup(arg1, arg2) {
  return window['go']['main']['App']['RestoreHostsBackup'](arg1, arg2);
}

export function SetHostsText(arg1, arg2) {
  return window['go']['main']['App']['SetHostsText'](arg1, arg2);
}

export function StartProfile(arg1) {
  return window['go']['main']['App']['StartProfile'](arg1);
}

export function StopAllProfiles() {
  return window['go']['main']['App']['StopAllProfiles']();
}

export function StopProfile(arg1) {
  return window['go']['main']['App']['StopProfile'](arg1);
}

export function UpdateHosts(arg1, arg2) {
  return window['go']['main']['App']['UpdateHosts'](arg1, arg2);
}
