// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddProfile(arg1:string,arg2:string,arg3:number):Promise<void>;

export function DedupHosts(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function ExportHostsToDialog(arg1:string):Promise<void>;

export function GetHostsText(arg1:string):Promise<string>;

export function GetProfiles():Promise<Array<main.ProfileState>>;

export function GetProxyAddress(arg1:string):Promise<string>;

export function GetProxyLogs(arg1:string,arg2:number):Promise<Array<main.ProxyLogEntry>>;

export function ImportHostsFromDialog(arg1:string):Promise<void>;

export function IsAdmin():Promise<boolean>;

export function LoadConfig():Promise<void>;

export function RenameProfile(arg1:string,arg2:string):Promise<void>;

export function SetHostsText(arg1:string,arg2:string):Promise<void>;

export function StartProfile(arg1:string):Promise<void>;

export function StopProfile(arg1:string):Promise<void>;

export function UpdateHosts(arg1:string,arg2:Array<main.HostEntry>):Promise<void>;
