// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddProfile(arg1:string,arg2:string,arg3:number):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function GetProfiles():Promise<Array<main.ProfileState>>;

export function LoadConfig():Promise<void>;

export function StartProfile(arg1:string):Promise<void>;

export function StopProfile(arg1:string):Promise<void>;

export function UpdateHosts(arg1:string,arg2:Array<main.HostEntry>):Promise<void>;
