// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';

export function AddProfile(arg1:string,arg2:string,arg3:number):Promise<void>;

export function AddProfileSubscription(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ClearHostsEntries(arg1:string):Promise<void>;

export function CreateHostsBackup(arg1:string):Promise<string>;

export function DedupHosts(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function ExportHostsToDialog(arg1:string):Promise<void>;

export function GetAuditLogs(arg1:number):Promise<Array<main.AuditLogEntry>>;

export function GetHostsText(arg1:string):Promise<string>;

export function GetProfileSubscriptions(arg1:string):Promise<Array<config.Subscription>>;

export function GetProfiles():Promise<Array<main.ProfileState>>;

export function GetProxyAddress(arg1:string):Promise<string>;

export function GetProxyLogs(arg1:string,arg2:number):Promise<Array<main.ProxyLogEntry>>;

export function GetSubscriptionRefreshHistory(arg1:string,arg2:number):Promise<Array<main.SubscriptionRefreshReport>>;

export function GetSubscriptionRefreshSettings(arg1:string):Promise<config.SubscriptionRefreshSettings>;

export function ImportHostsFromDialog(arg1:string):Promise<void>;

export function IsAdmin():Promise<boolean>;

export function IsSubscriptionRefreshRunning(arg1:string):Promise<boolean>;

export function ListHostsBackups(arg1:string):Promise<Array<main.BackupInfo>>;

export function LoadConfig():Promise<void>;

export function PreviewSubscriptionConflicts(arg1:string,arg2:string):Promise<main.SubscriptionConflictPreview>;

export function RefreshProfileSubscriptions(arg1:string):Promise<void>;

export function RefreshProfileSubscriptionsWithReport(arg1:string):Promise<main.SubscriptionRefreshReport>;

export function RefreshSingleProfileSubscription(arg1:string,arg2:string):Promise<void>;

export function RelaunchAsAdmin():Promise<void>;

export function RemoveProfileSubscription(arg1:string,arg2:string):Promise<void>;

export function RenameProfile(arg1:string,arg2:string):Promise<void>;

export function ResetHostsTemplate(arg1:string):Promise<void>;

export function ResolveSubscriptionConflicts(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RestoreHostsBackup(arg1:string,arg2:string):Promise<void>;

export function RetryFailedProfileSubscriptions(arg1:string):Promise<main.SubscriptionRefreshReport>;

export function SetAllProfileSubscriptionsEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetHostsText(arg1:string,arg2:string):Promise<void>;

export function SetProfileSubscriptionEnabled(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function StartProfile(arg1:string):Promise<void>;

export function StopAllProfiles():Promise<void>;

export function StopProfile(arg1:string):Promise<void>;

export function UpdateHosts(arg1:string,arg2:Array<main.HostEntry>):Promise<void>;

export function UpdateProfileSubscription(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UpdateSubscriptionRefreshSettings(arg1:string,arg2:boolean,arg3:number,arg4:number,arg5:number):Promise<void>;
