// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProfile(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddProfile'](arg1, arg2, arg3);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function StartProfile(arg1) {
  return window['go']['main']['App']['StartProfile'](arg1);
}

export function StopProfile(arg1) {
  return window['go']['main']['App']['StopProfile'](arg1);
}

export function UpdateHosts(arg1, arg2) {
  return window['go']['main']['App']['UpdateHosts'](arg1, arg2);
}
